[build]
builder = "nixpacks"
buildCommand = "npm install && npx prisma generate && npx prisma db push && npm run build"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "npm start"

[variables]